export const mainContentList = [
  {
    key: 1,
    title: 'Financial' + '\n' + 'Data',
    background: require('../../assets/png-images/Financial-Data/financial-data.png'),
    icon: require('../../assets/png-images/Financial-Data-Icon/financial-data-icon.png'),
    titleColor: '#FFFFFF',
    navigation: 'FinancialData',
  },
  {
    key: 2,
    title: 'Service and' + '\n' + 'Rewards',
    background: require('../../assets/png-images/Reward-Background/reward-background.png'),
    icon: require('../../assets/png-images/Reward/reward.png'),
    titleColor: '#212F3C',
    navigation: 'ServiceRewards',
  },
  {
    key: 3,
    title: 'Insurance',
    background: require('../../assets/png-images/Insurance-Background/insurance-background.png'),
    icon: require('../../assets/png-images/Insurance-Icon/insurance-icon.png'),
    titleColor: '#212F3C',
    navigation: 'Insurance',
  },
  {
    key: 4,
    title: 'Personal' + '\n' + 'Assets',
    background: require('../../assets/png-images/Personal-Assets/personal-assets.png'),
    icon: require('../../assets/png-images/Personal-Assets-Icon/personal-assets-icon.png'),
    titleColor: '#FFFFFF',
    navigation: 'PersonalAssets',
  },
  {
    key: 5,
    title: 'Government' + '\n' + 'Records',
    background: require('../../assets/png-images/Government-Records/government-records.png'),
    icon: require('../../assets/png-images/Government-Records-Icon/government-records-icon.png'),
    titleColor: '#FFFFFF',
    navigation: 'GovernmentRecords',
  },
  {
    key: 6,
    title: 'Personal' + '\n' + 'Organization',
    background: require('../../assets/png-images/Personal-Organisation/personal-organisation.png'),
    icon: require('../../assets/png-images/Personal-Organisation-Icon/personal-organisation-icon.png'),
    titleColor: '#FFFFFF',
    navigation: 'PersonalOrganisation',
  },
  {
    key: 7,
    title: 'Files',
    background: require('../../assets/png-images/Financial-Data/financial-data.png'),
    icon: require('../../assets/png-images/Government-Records-Icon/government-records-icon.png'),
    titleColor: '#FFFFFF',
    navigation: 'FileUploading',
  },
];
